# Generated by Django 3.2.7 on 2021-09-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptowallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
