# Generated by Django 3.2.8 on 2021-10-30 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('seed', models.TextField(blank=True, max_length=20000, null=True)),
                ('private_key', models.TextField(blank=True, max_length=20000, null=True)),
                ('public_key', models.TextField(blank=True, max_length=20000, null=True)),
                ('xprivate_key', models.TextField(blank=True, max_length=20000, null=True)),
                ('xpublic_key', models.TextField(blank=True, max_length=20000, null=True)),
                ('address', models.TextField(blank=True, max_length=20000, null=True)),
                ('wif', models.TextField(blank=True, max_length=20000, null=True)),
                ('balance', models.FloatField(default=0.0)),
                ('xpublic_key_prime', models.TextField(blank=True, max_length=20000, null=True)),
                ('is_pool', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_crypto_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
