# Generated by Django 3.2.7 on 2022-01-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptowallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='network_address',
            field=models.TextField(blank=True, max_length=65500, null=True),
        ),
    ]
