# Generated by Django 3.2.7 on 2022-03-09 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptowallet', '0007_auto_20220305_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='network',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Cancelled'), ('2', 'Awaiting Approval'), ('3', 'Rejected'), ('4', 'Processing'), ('5', 'Failure'), ('6', 'Completed')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DepositHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('coin', models.CharField(blank=True, max_length=255, null=True)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Cancelled'), ('2', 'Awaiting Approval'), ('3', 'Rejected'), ('4', 'Processing'), ('5', 'Failure'), ('6', 'Completed')], max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('addressTag', models.CharField(blank=True, max_length=255, null=True)),
                ('txId', models.CharField(blank=True, max_length=255, null=True)),
                ('insertTime', models.DateTimeField(blank=True, null=True)),
                ('transferType', models.IntegerField()),
                ('unlockConfirm', models.IntegerField()),
                ('walletType', models.IntegerField()),
                ('confirmTimes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_deposit', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crypto_wallet_deposit', to='cryptowallet.cryptowallet')),
            ],
        ),
    ]
