# Generated by Django 3.2.7 on 2021-12-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('gross_amount', models.FloatField(default=0.0)),
                ('net_amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='USD', max_length=250)),
                ('paymentId', models.CharField(max_length=250)),
                ('PayerID', models.CharField(max_length=250)),
                ('fees', models.FloatField(default=0.0)),
                ('admin_fees', models.FloatField(default=3.0)),
                ('is_success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
