# Generated by Django 3.2.7 on 2021-12-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_accounttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
